version: '3.7'
services:
  mysql57c:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userTransactions
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - spring.jpa.generate-ddl=true
    ports:
      - 3306:3306

  app:
    image: rudineypismo
    ports:
       - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql57c:3306/userTransactions?createDatabaseIfNotExist=true&serverTimeZone=UTC
    depends_on:
       - mysql57c